name: Publish to PyPI

on:
  release:
    types: [published]

# required for trusted publishing
permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install uv and set Python
      uses: astral-sh/setup-uv@v5
      with:
        python-version: "3.12"

    - name: Build and publish
      run: |
        uv build
        uv publish
